[project]
name = "aws-tsuyo-tsuyo"
version = "0.1.0"
description = "AWSのアーキテクチャアイコンを使用したぷよぷよ風ゲーム"
authors = [
    {name = "p0n"}
]
requires-python = ">=3.13"
dependencies = [
    "pygame>=2.5.0",
    "requests>=2.31.0",
    "pillow>=10.0.0",
]
